spring:
  application:
    name: tenant-demo
#  profiles:
#    active: default
  datasource:
    url: jdbc:mysql://192.168.6.104:3306/db_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: hckj@).2017
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
server:
  port: 8081
mybatis-plus:
  type-aliases-package: com.joeshaw.tenant_demo.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

